In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("/Users/savithrallapalli/Documents/NBA-Risk-Analysis/data/raw/player_stats_2025.csv")

print(df.shape)

(569, 67)

In [2]:
df.columns.tolist()

['PLAYER_ID',
 'PLAYER_NAME',
 'NICKNAME',
 'TEAM_ID',
 'TEAM_ABBREVIATION',
 'AGE',
 'GP',
 'W',
 'L',
 'W_PCT',
 'MIN',
 'FGM',
 'FGA',
 'FG_PCT',
 'FG3M',
 'FG3A',
 'FG3_PCT',
 'FTM',
 'FTA',
 'FT_PCT',
 'OREB',
 'DREB',
 'REB',
 'AST',
 'TOV',
 'STL',
 'BLK',
 'BLKA',
 'PF',
 'PFD',
 'PTS',
 'PLUS_MINUS',
 'NBA_FANTASY_PTS',
 'DD2',
 'TD3',
 'WNBA_FANTASY_PTS',
 'GP_RANK',
 'W_RANK',
 'L_RANK',
 'W_PCT_RANK',
 'MIN_RANK',
 'FGM_RANK',
 'FGA_RANK',
 'FG_PCT_RANK',
 'FG3M_RANK',
 'FG3A_RANK',
 'FG3_PCT_RANK',
 'FTM_RANK',
 'FTA_RANK',
 'FT_PCT_RANK',
 'OREB_RANK',
 'DREB_RANK',
 'REB_RANK',
 'AST_RANK',
 'TOV_RANK',
 'STL_RANK',
 'BLK_RANK',
 'BLKA_RANK',
 'PF_RANK',
 'PFD_RANK',
 'PTS_RANK',
 'PLUS_MINUS_RANK',
 'NBA_FANTASY_PTS_RANK',
 'DD2_RANK',
 'TD3_RANK',
 'WNBA_FANTASY_PTS_RANK',
 'TEAM_COUNT']

In [ ]:
df["performance_score"] = (
    df["PTS"] + 1.2*df["REB"] + 1.5*df["AST"] + 3*df["STL"] + 3*df["BLK"]
)

df["availability"] = df["GP"]/82

df["risk_adj_performance"] = (df["performance_score"]*df["availability"])

In [5]:
df[
    [
        "PLAYER_NAME",
        "TEAM_ABBREVIATION",
        "performance_score",
        "availability",
        "risk_adj_performance"
    ]
].sort_values(
    "risk_adj_performance",
    ascending=False
).head(20)

,PLAYER_NAME,TEAM_ABBREVIATION,performance_score,availability,risk_adj_performance
423,Nikola Jokić,DEN,67.34,0.853659,57.485366
490,Shai Gilgeous-Alexander,OKC,56.40,0.926829,52.273171
180,Giannis Antetokounmpo,MIL,60.73,0.817073,49.620854
241,James Harden,LAC,49.41,0.963415,47.602317
523,Trae Young,ATL,49.52,0.926829,45.896585
29,Anthony Edwards,MIN,46.59,0.963415,44.885488
263,Jayson Tatum,BOS,51.04,0.878049,44.815610
69,Cade Cunningham,DET,52.47,0.853659,44.791463
314,Karl-Anthony Towns,NYK,49.51,0.878049,43.472195
358,LeBron James,LAL,50.86,0.853659,43.417073
19,Alperen Sengun,HOU,44.51,0.926829,41.253171
146,Domantas Sabonis,SAC,48.08,0.853659,41.043902
141,Devin Booker,PHX,44.47,0.914634,40.673780
204,Ivica Zubac,LAC,41.37,0.975610,40.360976
38,Bam Adebayo,MIA,42.07,0.951220,40.017805
540,Tyler Herro,MIA,41.69,0.939024,39.147927
543,Tyrese Haliburton,IND,42.90,0.890244,38.191463
298,Josh Hart,NYK,39.67,0.939024,37.251098
498,Stephen Curry,GSW,43.28,0.853659,36.946341
169,Evan Mobley,CLE,41.96,0.865854,36.331220

In [6]:
df["performance_score_v2"] = (
    df["PTS"]
    + 1.2 * df["REB"]
    + 1.5 * df["AST"]
    + 3 * df["STL"]
    + 3 * df["BLK"]
    - 1.5 * df["TOV"]
)
df["risk_adj_v2"] = (
    df["performance_score_v2"]
    * df["availability"]
)
df[
    ["PLAYER_NAME", "risk_adj_v2"]
].sort_values(
    "risk_adj_v2",
    ascending=False
).head(20)

                 PLAYER_NAME  risk_adj_v2
423             Nikola Jokić    53.259756
490  Shai Gilgeous-Alexander    48.936585
180    Giannis Antetokounmpo    45.821463
241             James Harden    41.388293
263             Jayson Tatum    40.996098
29           Anthony Edwards    40.261098
314       Karl-Anthony Towns    39.916098
523               Trae Young    39.362439
69           Cade Cunningham    39.157317
358             LeBron James    38.679268
204              Ivica Zubac    38.019512
19            Alperen Sengun    37.638537
146         Domantas Sabonis    37.330488
38               Bam Adebayo    37.021463
141             Devin Booker    36.695122
543        Tyrese Haliburton    36.054878
540              Tyler Herro    35.485732
298                Josh Hart    34.293171
444            Pascal Siakam    33.939512
425           Nikola Vučević    33.802561