In [3]:
import pandas as pd

salary_df = pd.read_csv("/Users/savithrallapalli/Documents/NBA-Risk-Analysis/data/raw/salaries/nba_salaries.csv")

print(salary_df.head())
print(salary_df.columns.tolist())
print(salary_df.shape)

   Unnamed: 0        Player Name    Salary Position  Age     Team  GP  GS  \
0           0      Stephen Curry  48070014       PG   34      GSW  56  56
1           1          John Wall  47345760       PG   32      LAC  34   3
2           2  Russell Westbrook  47080179       PG   34  LAL/LAC  73  24
3           3       LeBron James  44474988       PF   38      LAL  55  54
4           4       Kevin Durant  44119845       PF   34  BRK/PHO  47  47

     MP    FG  ...  ORB  DRB  TRB  AST  STL  BLK  TOV   PF   PTS  \
0  34.7  10.0  ...  0.7  5.4  6.1  6.3  0.9  0.4  3.2  2.1  29.4
1  22.2   4.1  ...  0.4  2.3  2.7  5.2  0.8  0.4  2.4  1.7  11.4
2  29.1   5.9  ...  1.2  4.6  5.8  7.5  1.0  0.5  3.5  2.2  15.9
3  35.5  11.1  ...  1.2  7.1  8.3  6.8  0.9  0.6  3.2  1.6  28.9
4  35.6  10.3  ...  0.4  6.3  6.7  5.0  0.7  1.4  3.3  2.1  29.1

   Player-additional
0          curryst01
1           walljo01
2          westbru01
3          jamesle01
4          duranke01

[5 rows x 32 columns]
['Unnamed: 0', 'Player Name', 'Salary', 'Position', 'Age', 'Team', 'GP', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Player-additional']
(467, 32)

In [4]:
stats_df = pd.read_csv("/Users/savithrallapalli/Documents/NBA-Risk-Analysis/data/raw/statistics/player_stats_2022.csv")

print(stats_df.shape)
stats_df.head()

(539, 67)

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,TEAM_COUNT
0,1630639,A.J. Lawson,A.J.,1610612742,DAL,22.0,15,5,10,0.333,...,358,475,457,429,462,482,253,39,466,2
1,1631260,AJ Green,AJ,1610612749,MIL,23.0,35,27,8,0.771,...,498,454,518,392,309,455,253,39,436,1
2,1631100,AJ Griffin,AJ,1610612737,ATL,19.0,72,34,38,0.472,...,268,394,422,217,169,287,253,39,273,1
3,203932,Aaron Gordon,Aaron,1610612743,DEN,27.0,68,45,23,0.662,...,32,205,58,82,4,77,56,39,89,1
4,1628988,Aaron Holiday,Aaron,1610612737,ATL,26.0,63,32,31,0.508,...,315,377,356,415,212,413,253,39,416,1

In [5]:
stats_df[["PLAYER_NAME"]].head()

     PLAYER_NAME
0    A.J. Lawson
1       AJ Green
2     AJ Griffin
3   Aaron Gordon
4  Aaron Holiday

In [6]:
salary_df[["Player Name"]].head()

         Player Name
0      Stephen Curry
1          John Wall
2  Russell Westbrook
3       LeBron James
4       Kevin Durant

In [7]:
salary_df = salary_df.rename(
    columns={
        "Player Name": "PLAYER_NAME",
        "Salary": "SALARY"
    }
)

merged_df = stats_df.merge(
    salary_df[["PLAYER_NAME", "SALARY"]],
    on="PLAYER_NAME",
    how="inner"
)

print(merged_df.shape)
merged_df[["PLAYER_NAME", "SALARY"]].sample(10)

(458, 68)

                  PLAYER_NAME    SALARY
374                 Raul Neto   2463490
450               Xavier Moon    116986
424              Torrey Craig   5121951
153             Grayson Allen   8925000
210              Jaylen Brown  29776785
421             Thomas Bryant   1968175
176               Jaden Hardy   1017781
346  Nickeil Alexander-Walker   5009633
394            Scottie Barnes   7644600
252            Justin Holiday   5987975

In [8]:
merged_df.to_csv("/Users/savithrallapalli/Documents/NBA-Risk-Analysis/data/merged_nba_salary_stats_2022.csv", index=False)

In [8]:
merged_df["performance_score"] = (
    merged_df["PTS"]
    + 1.2 * merged_df["REB"]
    + 1.5 * merged_df["AST"]
    + 3 * merged_df["STL"]
    + 3 * merged_df["BLK"]
    - 1.5 * merged_df["TOV"]
)

merged_df["availability"] = merged_df["GP"] / 82

merged_df["risk_adj_performance"] = (
    merged_df["performance_score"]
    * merged_df["availability"]
)

merged_df["value_per_million"] = (
    merged_df["risk_adj_performance"]
    / (merged_df["SALARY"] / 1_000_000)
)
merged_df[
    [
        "PLAYER_NAME",
        "SALARY",
        "risk_adj_performance",
        "value_per_million"
    ]
].sort_values(
    "value_per_million",
    ascending=False
).head(20)

            PLAYER_NAME   SALARY  risk_adj_performance  value_per_million
373        RaiQuan Gray     5849              0.418293          71.515248
175       Jacob Gilyard     5849              0.296341          50.665321
402         Skylar Mays   116574              2.388293          20.487353
254       Justin Minaya    35096              0.695610          19.820200
141           Gabe York    32171              0.550610          17.115096
22         Anthony Lamb   694878             10.736585          15.451037
426           Tre Jones  1782621             23.982439          13.453470
400  Shaquille Harrison   134862              1.773171          13.148038
108        Desmond Bane  2130240             24.756098          11.621272
157   Immanuel Quickley  2316240             26.512683          11.446432
356    Orlando Robinson   386055              4.336220          11.232129
208            Jay Huff   116986              1.276220          10.909164
23        Austin Reaves  1563518             17.053659          10.907235
25          Ayo Dosunmu  1563518             16.936585          10.832357
178     Jaden McDaniels  2161440             22.380122          10.354265
321           Max Strus  1815677             18.770732          10.338145
84       Daniel Gafford  1930681             19.804390          10.257723
233      Jordan Goodwin  1280206             12.974634          10.134802
188     Jalen McDaniels  1930681             18.887805           9.782975
449        Xavier Cooks   140384              1.348780           9.607794

In [9]:
analysis_df = merged_df[
    (merged_df["GP"] >= 40) &
    (merged_df["SALARY"] >= 1_500_000)
].copy()

analysis_df[
    [
        "PLAYER_NAME",
        "SALARY",
        "GP",
        "risk_adj_performance",
        "value_per_million"
    ]
].sort_values(
    "value_per_million",
    ascending=False
).head(20)

           PLAYER_NAME   SALARY  GP  risk_adj_performance  value_per_million
426          Tre Jones  1782621  68             23.982439          13.453470
108       Desmond Bane  2130240  58             24.756098          11.621272
157  Immanuel Quickley  2316240  81             26.512683          11.446432
23       Austin Reaves  1563518  64             17.053659          10.907235
25         Ayo Dosunmu  1563518  80             16.936585          10.832357
178    Jaden McDaniels  2161440  79             22.380122          10.354265
321          Max Strus  1815677  80             18.770732          10.338145
84      Daniel Gafford  1930681  78             19.804390          10.257723
188    Jalen McDaniels  1930681  80             18.887805           9.782975
339      Naji Marshall  1782621  77             16.827317           9.439649
122       Drew Eubanks  1968175  78             18.149268           9.221369
445     Walker Kessler  2696400  74             24.844146           9.213821
342           Naz Reid  1930681  68             17.522439           9.075782
413       Terance Mann  1930681  81             17.019878           8.815479
239      Jose Alvarado  1563518  61             13.546463           8.664092
345      Nick Richards  1782621  65             15.322561           8.595524
16     Andrew Nembhard  2244111  75             18.512195           8.249233
439       Tyrese Maxey  2726880  60             21.790244           7.990907
261   Keita Bates-Diop  1878720  67             14.862561           7.911004
33             Bol Bol  2200000  70             17.039024           7.745011

In [10]:
from sklearn.linear_model import LinearRegression
import numpy as np
X = analysis_df[["SALARY"]]
y = analysis_df["risk_adj_performance"]
model = LinearRegression()

model.fit(X, y)

analysis_df["expected_performance"] = model.predict(X)

analysis_df["alpha"] = (
    analysis_df["risk_adj_performance"]
    - analysis_df["expected_performance"]
)

analysis_df[
    [
        "PLAYER_NAME",
        "SALARY",
        "risk_adj_performance",
        "expected_performance",
        "alpha"
    ]
].sort_values(
    "alpha",
    ascending=False
).head(20)

,PLAYER_NAME,SALARY,risk_adj_performance,expected_performance,alpha
20,Anthony Edwards,10733400,38.642561,17.379138,21.263423
114,Domantas Sabonis,21100000,42.737073,22.947399,19.789674
132,Evan Mobley,8478720,34.104878,16.168071,17.936807
241,Josh Giddey,6287400,32.235122,14.991037,17.244085
213,Jayson Tatum,30351780,43.867561,27.916852,15.950709
437,Tyrese Haliburton,4215120,29.359024,13.877943,15.481081
394,Scottie Barnes,7644600,31.100488,15.720036,15.380452
237,Jordan Poole,3901399,29.040000,13.709433,15.330567
170,Ja Morant,12119440,33.125976,18.123628,15.002348
250,Julius Randle,23760000,39.204268,24.376178,14.828091
224,Joel Embiid,33616770,43.978537,29.670591,14.307945
137,Franz Wagner,5258280,28.507317,14.438261,14.069057
89,Darius Garland,8920794,30.368415,16.405524,13.962890
157,Immanuel Quickley,2316240,26.512683,12.857989,13.654694
101,Dejounte Murray,17071120,34.391951,20.783348,13.608604
398,Shai Gilgeous-Alexander,30913750,40.642439,28.218705,12.423734
186,Jalen Green,9441840,28.907805,16.685396,12.222409
39,Brook Lopez,13906976,31.190488,19.083776,12.106712
108,Desmond Bane,2130240,24.756098,12.758081,11.998016
360,Paolo Banchero,11055120,29.440976,17.551945,11.889031

In [11]:
analysis_df[
    [
        "PLAYER_NAME",
        "SALARY",
        "risk_adj_performance",
        "expected_performance",
        "alpha"
    ]
].sort_values(
    "alpha",
    ascending=True
).head(20)

,PLAYER_NAME,SALARY,risk_adj_performance,expected_performance,alpha
27,Ben Simmons,35448672,13.245366,30.654570,-17.409204
124,Duncan Robinson,16902000,5.029756,20.692507,-15.662751
376,Richaun Holmes,11215260,3.293415,17.637962,-14.344547
275,Kevin Love,30556968,14.048293,28.027065,-13.978773
35,Bradley Beal,43279250,22.213415,34.860645,-12.647231
150,Gordon Hayward,30075000,15.859756,27.768184,-11.908428
448,Will Barton,15059712,9.171707,19.702950,-10.531243
172,JaVale McGee,5461219,4.404878,14.547266,-10.142388
92,Davon Reed,1902133,2.611463,12.635557,-10.024094
286,Kyle Lowry,28333334,16.848780,26.832674,-9.983894
252,Justin Holiday,5987975,5.015122,14.830205,-9.815083
144,Gary Harris,13000000,8.897561,18.596607,-9.699047
420,Theo Pinson,1968175,3.058537,12.671031,-9.612494
13,Amir Coffey,3395062,3.884146,13.437461,-9.553315
221,Joe Harris,18642857,12.219024,21.627582,-9.408558
290,Landry Shamet,9500000,7.434146,16.716636,-9.282489
378,Robert Covington,12307692,9.043902,18.224745,-9.180842
207,Jaxson Hayes,6803012,6.167317,15.267990,-9.100673
273,Kevin Durant,44119845,26.360122,35.312158,-8.952036
136,Frank Ntilikina,2036318,3.760000,12.707633,-8.947633

In [12]:
analysis_df.to_csv(
    "/Users/savithrallapalli/Documents/NBA-Risk-Analysis/data/nba_contract_valuation_2022.csv",
    index=False
)